### ISSUE TITLE
add project then went to remote build, spinner then got {}

### ISSUE THREAD

**Issue by illuminate3** [monaca/Localkit#23]
WTF? lol

Looks like your server is down ... the error I got when trying to push my project to the server with remote build got me a message that said .... {} and ok button.

then tried to upload and got no message and ok button.

funky stuff.

Ahhh, was this tied to the outage that just happened?

**Comment by andipavllo** [comment]
Hi @illuminate3 
I already replied you privately a few weeks ago at the email you sent to Monaca team but didn't get any response by you. Just in case, I'm going to write it once again:

```
We have already fixed this issue for some specific cases, during download/upload/remote build operations, it will be included in the next Localkit release, which will be soon.
If it's not related to those functionalities, could you please let us know how to replicate the issue and on which platform are you running Localkit?
Thank you for your cooperation.
```

That probably happens because the remote version of the project has been deleted. A workaround is to open your project dir and delete `.monaca/local_properties.json` file. At this point, you should be able to upload again.
Please let me know how it goes.

**Comment by andipavllo** [comment]
Should be fixed now, let me know if you still encounter the same issue.
