### ISSUE TITLE
Windows 10 open localkit but not showing-up 

### ISSUE THREAD

**Issue by TPGT00019** [monaca/Localkit#28]
Hi, I has installed version 3.4.4 but when click on icon then LocalKit UI not showing.
In Task Manager only running Backgroud processes.
How to fix, please.

Thanks & Brs,

**Comment by yong-asial** [comment]
@TPGT00019 
We will need following information for our investigation:
- what is your current windows 10 version?
- Is it a fresh installation?
- or you already had the previous version? Did it working fine on the previous version?
- Do you have some log generated?
  - The path to the log file could be configured at [Preferences] (https://docs.monaca.io/en/products_guide/monaca_localkit/overview/#preference-dialog) dialog

**Comment by TPGT00019** [comment]
My PC:
 - Windows 10 Home, 64 bit
 - Before that I had installed Version 3.4.3 but yesterday can't not open & not showing-up. After that, I uninstalled version 3.4.3 and install version 3.4.4 but not showing-up too. 
 - About log: Now the UI of Monaca Localkit not showing-up,  I haven't  any log. (In Task Manager only running Backgroud processes)

Thanks & Brs,

**Comment by yong-asial** [comment]
I see, maybe something wrong with the proxy or port configuration.

The path of preference is saved here - C:\Users\YOUR-USER-NAME\.cordova\localkit.db\preferences.db

- If you have configured the log, you should find something with `type:logFile, value:...`

- Otherwise, let's add following line to the file
```
{"type":"logFile","value":"C:\\log\\logs.txt","modifiedAt":{"$$date":1597687738623},"_id":"cq8L4FR1L4Ko1g4U"}
```
In this example, i created an empty file "logs.txt" under the "log" directory. Please also make sure you have proper permission to write the file.

After configuration, let's close Localkit and open it again.

**Comment by TPGT00019** [comment]
Hi,
I have this files. 
http://prntscr.com/uamv2q
and the content of preferences.db that here
http://prntscr.com/uamw35

I will update with above steps and check it again .
Thanks & Brs,

**Comment by TPGT00019** [comment]
Hi,
I had uninstall localkit =>  install NodeJs 14.9.0 (current) => reinstall localkit 3.4.4 same above steps but can not fix this.
(In "C:\\log\" folder, the logs.txt not exist)

Can check this again.

Thanks & Brs,

**Comment by yong-asial** [comment]
@TPGT00019 
Did you created the "log" folder? Also, please create an empty "logs.txt" before trying to open the application.

> In Task Manager only running Background processes.

Did you see any Localkit icon on the task bar?

> Before that I had installed Version 3.4.3 but yesterday

Anyway, it seems that something wrong with your current windows version since it used to work until yesterday. At the moment, it is really hard for us to troubleshoot this error since we could not reproduce it our end.
At least, it is working fine on our end. Below is our testing spec
- Windows 10 Pro 64 bit 
- Version 2004 
- OS Build 19041.450

There are previous version of Localkit in which you can try here - https://github.com/monaca/Localkit/releases
However, i doubt that it would solve the problem. To install it, you just need to go the version you wanna try and download the .EXE directly.

Other factors you might need to investigate
- What are the system changes made recently? Install any applications? windows update?
- Windows firewall or security? Any firewall or security rule that prevent running 3rd parties (or untrusted) software? Any protected file-write permission to a specific path?
- The localkit is 32-bit. I'm not sure do you have any windows setting that prevent running 32-bit software?

**Comment by TPGT00019** [comment]
@yong-asial 
Thanks to supports,
Lastest day the LocalKit good working is 2020/08/07 with v3.4.3
From yesterday I reworking but has error (Open by click LocalKit Icon but not showing-up) and I uninstall this version and install v 3.4.4

That trust, may be my computer something change (Update / firewall). I will check this again. If you has any info, please tell to me.

Thanks & Brs,

**Comment by yong-asial** [comment]
I see, just in case, I have just prepared the [64-bit Localkit](https://github.com/yong-asial/media/releases/download/1.0.0/localkit-setup-64-bit-3.4.4-20200903.exe) here. Not sure it resolve your problem tho.

(Note: I haven't fully tested all the features on this version yet)

**Comment by TPGT00019** [comment]
@yong-asial 
Many thanks for this supports. 
I has just installed this version 64-bit but Localkit not showing-up too.
Maybe my current windows environments has updated & wrong. I will check this again.

Thanks & Brs,

**Comment by TPGT00019** [comment]
@yong-asial ,
I had fixed this problem. 
This problem is monaca.json was empty  (I don't know why this suddenly empty)
http://prntscr.com/ubco18

So that, I had copy an other monaca.json file ( from other computer was good running) and open Localkit again and now it running good.

Thanks & Brs,
